agi_logger:
  verbosity: INFO
  logger:
    bag_path: /workspaces/logging/bags
    topics:
    - /clock
    - /fmu/out/vehicle_control_mode
    - /fmu/out/vehicle_status
    - /occupancy_map/inflated_voxel_map
    - /drone0/self_localization/pose
    - /navigation_runner/goal
    - /drone0/self_localization/path
    - /offboard_velocity_cmd
    - /drone1/RealSense_Camera/color/image_raw
    - /tf
    - /tf_static
    name: agi_test_log
    max_bag_size: 1
    override_qos: false
    qos_settings: cfg/qos_profiles.yaml
    compress: false
    duration: 10
    mcap: true
    auto_start: true
    auto_start_behavior: toggle_arm
    auto_start_topic: /fmu/out/vehicle_status
  tcp_file_communication:
    mode: ask
    server:
      port: 6000
      file_path: /workspaces/logging/bags/agi_log_20260128_115034_climb_test
    client:
      host: localhost
      port: 6000
      destination_path: ~/workspace/logging/bags/test_receive
